#!/usr/bin/env node
/**
 * Skyway Media — Meta Marketing API Comprehensive Pull
 * -----------------------------------------------------
 * READ-ONLY. Hits Meta's Graph API using a System User Token and writes
 * the full dataset Skyway OS needs into a single JSON file at:
 *   data/meta-pull.json
 *
 * Designed to run as a GitHub Action on a daily schedule (see
 * .github/workflows/meta-data-pull.yml).
 *
 * Per ad account, pulls:
 *   • Account metadata (status, currency, timezone, spend cap)
 *   • Account-level insights (spend / impressions / clicks / actions / conv value)
 *     for last 7d, last 30d, last 90d
 *   • Campaigns (id, name, status, objective, budget, bid strategy)
 *   • Campaign-level insights (30d)
 *   • Ad sets (id, name, status, budget, targeting summary, optimization goal)
 *   • Ads (id, name, status, creative ref, tracking specs)
 *
 * Authentication: env var META_TOKEN — a System User Token generated by
 * Sara Rose in Business Manager. The token only needs `ads_read` and
 * `business_management` scopes — NO write permissions.
 *
 * Read-only guarantee:
 *   This script uses HTTP GET requests only. There are zero POST, PUT,
 *   or DELETE calls anywhere. Meta's API rejects mutation attempts on
 *   GET endpoints at the server side. Verify by grepping the file:
 *   "method: 'POST'", "method: 'PUT'", "method: 'DELETE'" all return
 *   zero matches.
 *
 * Cost: $0/mo. Replaces Supermetrics for Meta entirely.
 */

const fs = require('node:fs');
const path = require('node:path');

const TOKEN = process.env.META_TOKEN;
const API_VERSION = process.env.META_API_VERSION || 'v23.0';
const API = `https://graph.facebook.com/${API_VERSION}`;
const OUT_PATH = path.join('data', 'meta-pull.json');
const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 2000;

if (!TOKEN) {
  console.error('FATAL: META_TOKEN env var is required');
  console.error('       Generate a System User Token in Meta Business Manager');
  console.error('       and add it to GitHub repo secrets as META_TOKEN.');
  process.exit(1);
}

// ----- Helpers -------------------------------------------------------------

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

/**
 * Fetch a single URL with retry on transient errors. Always a GET — never
 * sends a body, never modifies anything.
 */
async function getJson(url) {
  const sep = url.includes('?') ? '&' : '?';
  const fullUrl = `${url}${sep}access_token=${encodeURIComponent(TOKEN)}`;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const res = await fetch(fullUrl, { method: 'GET' });
      const json = await res.json();
      if (json.error) {
        const e = json.error;
        // Rate limit codes: retry; everything else: throw
        const isRateLimit = (e.code === 17 || e.code === 4 || e.code === 32 || e.code === 613);
        if (isRateLimit && attempt < MAX_RETRIES) {
          console.warn(`  rate-limited (code ${e.code}), retrying in ${RETRY_DELAY_MS}ms...`);
          await sleep(RETRY_DELAY_MS * attempt);
          continue;
        }
        throw new Error(`Meta API error (code ${e.code}): ${e.message}`);
      }
      return json;
    } catch (e) {
      if (attempt < MAX_RETRIES) {
        console.warn(`  ${e.message} — retrying in ${RETRY_DELAY_MS}ms...`);
        await sleep(RETRY_DELAY_MS * attempt);
        continue;
      }
      throw e;
    }
  }
}

/** Walk Meta's `paging.next` chain and return all collected `data`. */
async function getAllPaged(url) {
  const items = [];
  let next = url;
  while (next) {
    const json = await getJson(next);
    if (Array.isArray(json.data)) items.push(...json.data);
    // paging.next from Meta already includes access_token; replace it to be safe
    if (json.paging && json.paging.next) {
      const nextUrl = new URL(json.paging.next);
      nextUrl.searchParams.delete('access_token');
      next = nextUrl.toString();
    } else {
      next = null;
    }
  }
  return items;
}

// ----- Account-level pulls -------------------------------------------------

async function listAdAccounts() {
  // /me/adaccounts returns every ad account the System User has access to.
  const fields = [
    'id', 'name', 'account_status', 'currency', 'timezone_name',
    'disable_reason', 'spend_cap', 'amount_spent', 'business'
  ].join(',');
  return getAllPaged(`${API}/me/adaccounts?fields=${fields}&limit=100`);
}

async function pullAccountInsights(acctId, datePreset) {
  const fields = [
    'spend', 'impressions', 'clicks', 'ctr', 'cpc', 'cpm', 'reach',
    'actions', 'action_values', 'cost_per_action_type'
  ].join(',');
  const url = `${API}/${acctId}/insights?fields=${fields}&date_preset=${datePreset}&limit=100`;
  // Account-level insights return a single row or none; getAllPaged is fine.
  const rows = await getAllPaged(url);
  return rows[0] || null;
}

async function pullCampaigns(acctId) {
  const fields = [
    'id', 'name', 'status', 'effective_status', 'objective',
    'daily_budget', 'lifetime_budget', 'budget_remaining',
    'bid_strategy', 'buying_type', 'created_time', 'updated_time',
    'start_time', 'stop_time'
  ].join(',');
  return getAllPaged(`${API}/${acctId}/campaigns?fields=${fields}&limit=200`);
}

async function pullCampaignInsights(acctId, datePreset) {
  const fields = [
    'campaign_id', 'campaign_name', 'spend', 'impressions', 'clicks',
    'ctr', 'cpc', 'cpm', 'reach', 'actions', 'action_values',
    'cost_per_action_type'
  ].join(',');
  return getAllPaged(
    `${API}/${acctId}/insights?level=campaign&fields=${fields}&date_preset=${datePreset}&limit=500`
  );
}

async function pullAdSets(acctId) {
  const fields = [
    'id', 'name', 'campaign_id', 'status', 'effective_status',
    'daily_budget', 'lifetime_budget', 'bid_strategy', 'bid_amount',
    'optimization_goal', 'billing_event', 'targeting',
    'start_time', 'end_time'
  ].join(',');
  return getAllPaged(`${API}/${acctId}/adsets?fields=${fields}&limit=200`);
}

async function pullAdSetInsights(acctId, datePreset) {
  const fields = [
    'adset_id', 'adset_name', 'campaign_id', 'spend', 'impressions',
    'clicks', 'ctr', 'cpc', 'cpm', 'actions', 'action_values',
    'cost_per_action_type'
  ].join(',');
  return getAllPaged(
    `${API}/${acctId}/insights?level=adset&fields=${fields}&date_preset=${datePreset}&limit=500`
  );
}

async function pullAds(acctId) {
  const fields = [
    'id', 'name', 'campaign_id', 'adset_id', 'status', 'effective_status',
    'creative{id,name,object_story_spec,thumbnail_url}',
    'tracking_specs', 'created_time', 'updated_time'
  ].join(',');
  return getAllPaged(`${API}/${acctId}/ads?fields=${fields}&limit=200`);
}

async function pullAdInsights(acctId, datePreset) {
  const fields = [
    'ad_id', 'ad_name', 'adset_id', 'campaign_id', 'spend', 'impressions',
    'clicks', 'ctr', 'cpc', 'cpm', 'actions', 'action_values',
    'cost_per_action_type'
  ].join(',');
  return getAllPaged(
    `${API}/${acctId}/insights?level=ad&fields=${fields}&date_preset=${datePreset}&limit=500`
  );
}

// ----- Main ----------------------------------------------------------------

async function main() {
  const startedAt = new Date();
  console.log(`Skyway Meta pull starting at ${startedAt.toISOString()}`);
  console.log(`API version: ${API_VERSION}`);

  let adAccounts;
  try {
    adAccounts = await listAdAccounts();
    console.log(`Found ${adAccounts.length} ad accounts visible to this token`);
  } catch (e) {
    console.error('FATAL: could not list ad accounts:', e.message);
    process.exit(1);
  }

  const out = {
    generated_at: startedAt.toISOString(),
    api_version: API_VERSION,
    account_count: adAccounts.length,
    accounts: []
  };
  let errors = 0;

  for (const acct of adAccounts) {
    const acctId = acct.id;
    const acctName = acct.name || '';
    console.log(`[${acctId}] ${acctName}`);

    const accountData = {
      account_id: acctId,
      account_name: acctName,
      account_status: acct.account_status,
      effective_status: acct.disable_reason || 'ACTIVE',
      currency: acct.currency,
      timezone: acct.timezone_name,
      spend_cap: acct.spend_cap,
      amount_spent: acct.amount_spent,
      business: acct.business || null,
      insights: { last_7d: null, last_30d: null, last_90d: null },
      campaigns: [],
      campaign_insights_30d: [],
      adsets: [],
      adset_insights_30d: [],
      ads: [],
      ad_insights_30d: [],
      errors: []
    };

    // Account-level insights for 3 windows
    for (const w of ['last_7d', 'last_30d', 'last_90d']) {
      try {
        accountData.insights[w] = await pullAccountInsights(acctId, w);
      } catch (e) {
        accountData.errors.push({ query: `account_insights ${w}`, error: e.message });
      }
    }
    // Campaigns + 30d campaign insights
    try { accountData.campaigns = await pullCampaigns(acctId); }
    catch (e) { accountData.errors.push({ query: 'campaigns', error: e.message }); }
    try { accountData.campaign_insights_30d = await pullCampaignInsights(acctId, 'last_30d'); }
    catch (e) { accountData.errors.push({ query: 'campaign_insights', error: e.message }); }
    // Ad sets + 30d insights
    try { accountData.adsets = await pullAdSets(acctId); }
    catch (e) { accountData.errors.push({ query: 'adsets', error: e.message }); }
    try { accountData.adset_insights_30d = await pullAdSetInsights(acctId, 'last_30d'); }
    catch (e) { accountData.errors.push({ query: 'adset_insights', error: e.message }); }
    // Ads + 30d insights
    try { accountData.ads = await pullAds(acctId); }
    catch (e) { accountData.errors.push({ query: 'ads', error: e.message }); }
    try { accountData.ad_insights_30d = await pullAdInsights(acctId, 'last_30d'); }
    catch (e) { accountData.errors.push({ query: 'ad_insights', error: e.message }); }

    if (accountData.errors.length > 0) errors++;
    console.log(`  campaigns=${accountData.campaigns.length}, adsets=${accountData.adsets.length}, ads=${accountData.ads.length}, errors=${accountData.errors.length}`);
    out.accounts.push(accountData);
  }

  // Write the output JSON
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, JSON.stringify(out, null, 2));

  const elapsedS = ((new Date()).getTime() - startedAt.getTime()) / 1000;
  console.log('---');
  console.log(`Done in ${elapsedS.toFixed(1)}s`);
  console.log(`Accounts:        ${out.accounts.length}`);
  console.log(`With errors:     ${errors}`);
  console.log(`Output:          ${OUT_PATH}`);
}

main().catch(err => {
  console.error('FATAL:', err);
  process.exit(1);
});
